### ISSUE TITLE
Support for gatling projects written with maven

### ISSUE THREAD

**Issue by anandudas** [Abiy/distGatling#1]
Is it possible to use distGatling with gatling projects which are written with maven?

There is no file named gatling.sh in maven project, so confused how to edit the `application.yml`

**Comment by Abiy** [comment]
Hi, 

Once you setup the cluster properly, you can just upload the simulation file and start running it in a distributed mode.  If your simulation script depends on an external library then you can upload the library as a plugin and it would be in the class path when the simulation runs. 

The application.yml file is part of the cluster setup and should be available under gatling-rest/arc/main/resources/application.xml.  

You can also override any of these properties via -D parameter when you start the master and workers.

Thanks,

**Comment by Abiy** [comment]
feature for running simulations that are packaged into uber jar via maven is now included.
